# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import uic
from PyQt5.QtWidgets import *

def import_clicked(self):
    self.label.setText("haha")
    self.label.setPixmap(QtGui.QPixmap(".\\default.png"))

class MyGUI(QMainWindow):
    def __init__(self):
        super(MyGUI,self).__init__()
        uic.loadUi("\\gui.ui",self)
        self.show()
        
def main():
    app=QApplication([])
    windows = MyGUI()
    app.exec_()
    
if __name__ == '__main__':
    main()